from django.urls import path

from .views import (
    CourseListAPIView,
    CourseDetailAPIView,
    CourseCreateAPIView,
    CourseUpdateAPIView,
    CourseDeleteAPIView,
    EnrollCourseAPIView,
    MyEnrollmentsAPIView,
    CompleteLessonAPIView,
    MyProgressAPIView,
    MyCoursesAPIView,
    LessonCreateAPIView,
    LessonListAPIView,
    LessonDeleteAPIView,
    LessonDetailAPIView,
    LessonUpdateAPIView,
    InstructorAnalyticsAPIView,
    ReviewListCreateAPIView,
    WishlistCreateAPIView,
    WishlistListAPIView,
    CreatePaymentAPIView,
    VerifyPaymentAPIView,
    PaymentHistoryAPIView,
)

urlpatterns = [
    path(
        "",
        CourseListAPIView.as_view(),
        name="course-list",
    ),
    path(
        "create/",
        CourseCreateAPIView.as_view(),
        name="course-create",
    ),
    path(
        "<int:pk>/update/",
        CourseUpdateAPIView.as_view(),
        name="course-update",
    ),
    path(
        "<int:pk>/delete/",
        CourseDeleteAPIView.as_view(),
        name="course-delete",
    ),
    path(
        "lessons/<int:pk>/",
        LessonDetailAPIView.as_view(),
        name="lesson-detail",
    ),
    path(
        "lessons/<int:pk>/update/",
        LessonUpdateAPIView.as_view(),
        name="lesson-update",
    ),
    path(
        "<int:pk>/enroll/",
        EnrollCourseAPIView.as_view(),
        name="course-enroll",
    ),
    path(
        "my-enrollments/",
        MyEnrollmentsAPIView.as_view(),
        name="my-enrollments",
    ),
    path(
        "lessons/<int:pk>/complete/",
        CompleteLessonAPIView.as_view(),
        name="lesson-complete",
    ),
    path(
        "my-progress/",
        MyProgressAPIView.as_view(),
        name="my-progress",
    ),
    path(
        "my-courses/",
        MyCoursesAPIView.as_view(),
        name="my-courses",
    ),
    path(
        "<int:pk>/lessons/create/",
        LessonCreateAPIView.as_view(),
        name="lesson-create",
    ),
    path(
        "<int:pk>/lessons/",
        LessonListAPIView.as_view(),
        name="lesson-list",
    ),
    path(
        "lessons/<int:pk>/delete/",
        LessonDeleteAPIView.as_view(),
        name="lesson-delete",
    ),
    path(
        "analytics/",
        InstructorAnalyticsAPIView.as_view(),
        name="analytics",
    ),
    path(
        "<int:course_id>/reviews/",
        ReviewListCreateAPIView.as_view(),
        name="course-reviews",
    ),
    path(
        "<int:pk>/wishlist/",
        WishlistCreateAPIView.as_view(),
        name="course-wishlist",
    ),
    path(
        "my-wishlist/",
        WishlistListAPIView.as_view(),
        name="my-wishlist",
    ),
    path(
        "<int:pk>/payment/",
        CreatePaymentAPIView.as_view(),
        name="course-payment",
    ),
    path(
        "<int:pk>/verify-payment/",
        VerifyPaymentAPIView.as_view(),
        name="verify-payment",
    ),
    path(
        "payments/",
        PaymentHistoryAPIView.as_view(),
        name="payment-history",
    ),
    path(
        "<int:pk>/",
        CourseDetailAPIView.as_view(),
        name="course-detail",
    ),
]
